// Bread class and breadDatabase remain the same
class Bread {
  final String name;
  final String imagePath;
  final String origin;
  final String description;
  final List facts;
  final List ingredients;

  Bread({
    required this.name,
    required this.imagePath,
    required this.origin,
    required this.description,
    required this.facts,
    required this.ingredients,
  });

  factory Bread.fromJson(Map<String, dynamic> json) {
    return Bread(
      name: json['name'],
      imagePath: json['imagePath'],
      origin: json['origin'],
      description: json['description'],
      facts: List.from(json['facts']),
      ingredients: List.from(json['ingredients']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'imagePath': imagePath,
      'origin': origin,
      'description': description,
      'facts': facts,
      'ingredients': ingredients,
    };
  }
}

final List<Bread> breadDatabase = [
  Bread(
    name: 'Sourdough',
    imagePath: 'assets/images/sourdough.jpg',
    origin: 'Ancient Egypt, around 1500 BCE',
    description:
        'Sourdough bread is made by the fermentation of dough using naturally occurring lactobacilli and yeast. It has a slightly sour taste not present in most breads made with baker\'s yeast and better inherent keeping qualities than other breads due to the lactic acid produced by the lactobacilli.',
    facts: [
      'Sourdough bread is one of the oldest forms of leavened bread, dating back to ancient Egypt.',
      'The oldest sourdough bread was excavated in Switzerland and dates back to 3700 BCE.',
      'San Francisco sourdough is a famous variation that uses a specific strain of bacteria called Lactobacillus sanfranciscensis.',
      'During the California Gold Rush, sourdough was so essential to the diet of miners that they would sleep with their starter dough to keep it warm and alive.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Salt',
      'Sourdough starter (wild yeast and bacteria culture)',
    ],
  ),
  Bread(
    name: 'Baguette',
    imagePath: 'assets/images/baguette.jpg',
    origin: 'France, 19th century',
    description:
        'The baguette is a long, thin loaf of French bread that is commonly made from basic lean dough. It is distinguishable by its length and crisp crust. A typical baguette is about 65 cm long, and weighs about 250 g.',
    facts: [
      'The word "baguette" simply means "wand" or "stick" in French.',
      'There are laws in France regulating the ingredients and shape of a true baguette.',
      'A traditional French baguette contains only flour, water, salt, and yeast.',
      'During the French Revolution, bakers would work through the night to ensure fresh bread was available in the morning.',
      'The distinctive slashes on top of a baguette (called "scoring") help control the expansion of the dough during baking.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Salt',
      'Yeast',
    ],
  ),
  Bread(
    name: 'Ciabatta',
    imagePath: 'assets/images/ciabatta.jpg',
    origin: 'Italy, 1982',
    description:
        'Ciabatta is an Italian white bread made from wheat flour, water, salt, yeast and olive oil. It was first produced in 1982 by a baker in Verona, Italy, in response to the popularity of French baguettes. Ciabatta is somewhat elongated, broad and flat, and is baked in many variations.',
    facts: [
      'Ciabatta was specifically created in 1982 by a baker named Arnaldo Cavallari to compete with the popularity of French baguettes.',
      'The name "ciabatta" means "slipper" in Italian, referring to its shape.',
      'The dough is very wet and sticky compared to many other bread doughs.',
      'It has a crisp crust but a soft, porous texture inside with large irregular holes.',
      'Ciabatta is perfect for making sandwiches, especially the Italian panini.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Salt',
      'Yeast',
      'Olive oil',
    ],
  ),
  Bread(
    name: 'Naan',
    imagePath: 'assets/images/naan.jpg',
    origin: 'India, around 1300 CE',
    description:
        'Naan is a leavened, oven-baked flatbread found in the cuisines mainly of Western Asia, South Asia, Indonesia, Myanmar and the Caribbean. It resembles pita bread but is softer in texture. Traditionally, it is baked in a tandoor, or cylindrical clay oven.',
    facts: [
      'The word "naan" comes from Persian, meaning "bread".',
      'Traditional naan is cooked by slapping the dough onto the hot walls of a tandoor oven.',
      'Each region has its own variations, such as garlic naan, butter naan, or cheese naan.',
      'In India, naan was originally a food of the nobles and the royal court as most common people did not have access to tandoor ovens.',
      'Unlike most Indian bread, naan contains yeast and sometimes eggs and yogurt, which gives it its distinctive texture.',
    ],
    ingredients: [
      'Flour',
      'Yogurt',
      'Butter',
      'Yeast',
      'Water',
      'Salt',
    ],
  ),
  Bread(
    name: 'Pumpernickel',
    imagePath: 'assets/images/pumpernickel.jpg',
    origin: 'Germany, 16th century',
    description:
        'Pumpernickel is a dense, dark German bread traditionally made with coarse rye flour. It has a dark color and slightly sweet taste due to the long, slow baking process which can take up to 24 hours. Traditional Westphalian pumpernickel contains no artificial coloring and is made using a sourdough starter.',
    facts: [
      'The name "pumpernickel" might come from the German words "pumpern" (to break wind) and "Nickel" (a form of the name Nicholas, commonly associated with a goblin or devil), reflecting the bread\'s reputation for being difficult to digest.',
      'Traditional pumpernickel bread can take up to 24 hours to bake at a low temperature.',
      'The dark color comes naturally from the Maillard reaction during the long baking process, not from added coloring.',
      'It was a staple food for peasants in the Westphalia region of Germany for several centuries.',
      'Unlike most breads, traditional pumpernickel doesn\'t use commercial yeast but relies on natural sourdough fermentation.',
    ],
    ingredients: [
      'Rye flour',
      'Rye berries',
      'Water',
      'Salt',
      'Sourdough starter',
    ],
  ),
  Bread(
    name: 'Challah',
    imagePath: 'assets/images/challah.jpg',
    origin: 'Jewish communities in Eastern Europe, 15th century',
    description:
        'Challah is a special Jewish bread, usually braided and typically eaten on ceremonial occasions such as Shabbat and major Jewish holidays. The simple dough is made with eggs, water, flour, yeast and salt. The braiding of the bread has symbolic importance and the preparation is steeped in tradition.',
    facts: [
      'Challah\'s braided shape is said to symbolize love, with arms intertwined.',
      'For Rosh Hashanah (Jewish New Year), challah is often baked in a round shape to symbolize the cycle of the year.',
      'The word "challah" originally referred to the portion of bread set aside as an offering in biblical times.',
      'It is customary to put two loaves on the Sabbath table, commemorating the double portion of manna that fell for the Israelites on Friday during their exodus from Egypt.',
      'Traditional challah recipes call for the bread to be brushed with an egg wash before baking, giving it its distinctive glossy crust.',
    ],
    ingredients: [
      'Flour',
      'Eggs',
      'Water',
      'Yeast',
      'Sugar',
      'Salt',
      'Oil',
    ],
  ),
  Bread(
    name: 'Focaccia',
    imagePath: 'assets/images/focaccia.jpg',
    origin: 'Italy, Ancient Rome',
    description:
        'Focaccia is a flat oven-baked Italian bread similar in style and texture to pizza dough. It\'s usually seasoned with olive oil, salt, and sometimes herbs or other toppings. Focaccia can be used as a side to many meals, as a base for pizza, or as sandwich bread.',
    facts: [
      'Focaccia is an early prototype of modern pizza and dates back to ancient Rome.',
      'The name comes from the Latin word "focus" meaning "hearth" or "place for baking".',
      'In Genoa, Italy, there\'s a version called "Focaccia di Recco" which is filled with cheese.',
      'Traditional focaccia has dimples all over its surface, which are made with fingertips and help collect the olive oil and flavors.',
      'It\'s often topped with herbs, olives, vegetables, or salt crystals before baking.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Yeast',
      'Salt',
      'Olive oil',
      'Various toppings (rosemary, sea salt, olives, etc.)',
    ],
  ),
  Bread(
    name: 'Pita',
    imagePath: 'assets/images/pita.jpg',
    origin: 'Middle East, around 2500 BCE',
    description:
        'Pita is a family of round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas. It has a hollow center that forms a pocket during baking, perfect for holding fillings when making sandwiches.',
    facts: [
      'The word "pita" comes from Greek, though the bread itself predates the Greek language.',
      'The pocket in pita bread forms when water vapor in the dough rapidly expands during high heat baking.',
      'In Turkish cuisine, a variety of pita called "pide" is boat-shaped and typically topped with ingredients before baking.',
      'Pita bread is one of the oldest breads in the world, dating back at least 4,000 years.',
      'In many Middle Eastern restaurants, pita is served fresh from the oven, slightly inflated like a balloon.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Salt',
      'Yeast',
      'Olive oil (sometimes)',
    ],
  ),
  Bread(
    name: 'Brioche',
    imagePath: 'assets/images/brioche.jpg',
    origin: 'France, around 15th century',
    description:
        'Brioche is a French bread of French origin that is similar to a highly enriched pastry, and whose high egg and butter content gives it a rich and tender crumb. It has a dark, golden, and flaky crust, frequently accentuated by an egg wash applied after proofing.',
    facts: [
      'Brioche is classified as a Viennoiserie, which means it is a baked good made from a yeast-leavened dough in the same manner as bread, but with added ingredients that increase the fat content.',
      'The phrase "Let them eat cake" attributed to Marie Antoinette may have actually been "Let them eat brioche" in the original French.',
      'Traditional brioche contains butter, eggs, and milk, making it much richer than most breads.',
      'It takes much longer to rise than regular bread due to its high fat content.',
      'Brioche comes in various shapes including the classic brioche à tête (with a small ball on top) and brioche Nanterre (loaf form).',
    ],
    ingredients: [
      'Flour',
      'Butter',
      'Eggs',
      'Sugar',
      'Milk',
      'Yeast',
      'Salt',
    ],
  ),
  Bread(
    name: 'Rye Bread',
    imagePath: 'assets/images/rye.jpg',
    origin: 'Northern and Eastern Europe, Middle Ages',
    description:
        'Rye bread is made with various percentages of rye flour, and is particularly popular in Northern and Eastern European cuisines. It can range from light and mild to very dark, dense, and strongly flavored. Many varieties use sourdough starters and can incorporate caraway or dill seeds.',
    facts: [
      'Rye grain was originally considered a weed growing among wheat until its value as a crop was recognized.',
      'Rye bread stays fresh longer than wheat bread and has a lower glycemic index.',
      'In Finland, rye bread is the national bread and Finns consume about 40 kg per person per year.',
      'Rye bread is resistant to cutting when fresh and is often preferred a day old.',
      'During the Middle Ages, wheat was expensive and reserved for the wealthy, while rye bread was consumed by the common people.',
    ],
    ingredients: [
      'Rye flour',
      'Water',
      'Salt',
      'Sourdough starter or yeast',
      'Caraway seeds (optional)',
    ],
  ),
  Bread(
    name: 'Chapati',
    imagePath: 'assets/images/chapati.jpg',
    origin: 'Indian subcontinent, potentially Indus Valley Civilization',
    description:
        'Chapati is an unleavened flatbread originating from the Indian subcontinent. It is a staple in India, Nepal, Bangladesh, Pakistan, Sri Lanka, East Africa, and the Caribbean. Chapatis are made of whole-wheat flour, water, and salt, and are cooked on a tava (flat skillet).',
    facts: [
      'Chapati is a form of Roti, and the names are often used interchangeably.',
      'The word "chapat" in Marathi means "slap" or "flat," referring to the traditional method of shaping the dough.',
      'Carbonized wheat grains found at Mohenjo-daro excavations suggest similar flatbreads existed as far back as the Indus Valley Civilization.',
      'Chapatis puff up dramatically when cooked directly over a flame after the tava, creating a "phulka".',
      'They are commonly used to scoop up curries and dishes.',
    ],
    ingredients: [
      'Whole wheat flour (Atta)',
      'Water',
      'Salt',
      'Ghee or oil (optional)',
    ],
  ),
  Bread(
    name: 'Tortilla',
    imagePath: 'assets/images/tortilla.jpg',
    origin: 'Mesoamerica (Mexico/Central America), potentially 3000 BCE',
    description:
        'A tortilla is a round, thin, unleavened flatbread traditionally made from corn or wheat flour. It is a staple of Mexican and Central American cuisines and is used as a base for dishes like tacos, burritos, quesadillas, and enchiladas.',
    facts: [
      'Corn tortillas date back thousands of years to indigenous groups like the Mayans and Aztecs.',
      'The Spanish conquistadors gave the corn flatbread the name "tortilla," meaning "little cake" in Spanish.',
      'Traditional corn tortillas are made from masa, a dough prepared from dried corn treated with an alkaline solution (nixtamalization).',
      'Wheat flour tortillas became popular in northern Mexico and the United States.',
      'In Spain, the word "tortilla" refers to an egg omelet-like dish, not the flatbread.',
    ],
    ingredients: [
      'Corn flour (Masa Harina) or Wheat flour',
      'Water',
      'Salt',
      'Shortening (lard or oil) (optional)',
    ],
  ),
  Bread(
    name: 'Injera',
    imagePath: 'assets/images/injera.jpg',
    origin: 'Ethiopia and Eritrea, thousands of years ago',
    description:
        'Injera is a sour fermented pancake-like flatbread with a slightly spongy texture, traditionally made of teff flour. It is a staple food in Ethiopia and Eritrea and serves as both a food and an edible utensil for scooping up stews and dishes.',
    facts: [
      'Injera is typically made from teff, an ancient grain believed to be the smallest in the world, native to the Ethiopian Highlands.',
      'The characteristic sour taste comes from a several-day fermentation process of the teff batter.',
      'It is traditionally cooked on a large, round griddle called a "mitad".',
      'The top surface of injera is porous, perfect for soaking up sauces.',
      'While traditionally made only with teff, blends with other flours like barley, wheat, or rice are sometimes used.',
    ],
    ingredients: [
      'Teff flour',
      'Water',
      'Ersho (starter from previous fermentation)',
    ],
  ),
  Bread(
    name: 'Irish Soda Bread',
    imagePath: 'assets/images/irish_soda_bread.jpg',
    origin: 'Ireland, early 19th century',
    description:
        'Irish soda bread is a quick bread traditionally made with wheat flour, buttermilk, baking soda, and salt. It uses baking soda as a leavening agent activated by the lactic acid in the buttermilk, rather than yeast. It is typically a round loaf with a cross cut into the top.',
    facts: [
      'The use of baking soda (bicarbonate of soda) became popular when it was introduced to the UK in the 1830s.',
      'It became a staple in Ireland due to the ready availability of soft wheat flour and buttermilk.',
      'The cross cut on top is traditionally believed to ward off evil or let the fairies out, but it also helps the bread cook evenly.',
      'Traditional recipes are very simple; additions like sugar, eggs, or dried fruit are modern variations.',
      'It was often baked on a griddle or in a pot over an open hearth in homes without ovens.',
    ],
    ingredients: [
      'Wheat flour',
      'Buttermilk',
      'Baking soda',
      'Salt',
    ],
  ),
  Bread(
    name: 'Pretzel',
    imagePath: 'assets/images/pretzel.jpg',
    origin: 'Europe (possibly Germany or Italy), Middle Ages',
    description:
        'A pretzel is a type of baked bread product made from dough, most commonly shaped into a knot. It is typically seasoned with salt and can be either soft and chewy or hard and crunchy.',
    facts: [
      'One popular legend says pretzels were invented by an Italian monk in 610 AD, shaped like praying arms as a reward for students.',
      'The word "pretzel" likely comes from the Latin word "bracellae" meaning "little arms".',
      'In Bavaria, the pretzel (Brezn) is a significant part of the local culture and cuisine.',
      'Soft pretzels are briefly boiled in a lye or baking soda solution before baking, which contributes to their distinctive crust and color.',
      'Pretzels were once a symbol of the baker\'s guild.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Lye or baking soda solution (for boiling)',
    ],
  ),
  Bread(
    name: 'Bagel',
    imagePath: 'assets/images/bagel.jpg',
    origin: 'Jewish communities in Poland, 17th century',
    description:
        'A bagel is a bread roll, typically shaped by hand into the form of a ring, which is first boiled for a short time in water and then baked. The result is a dense, chewy interior with a browned and sometimes crisp exterior.',
    facts: [
      'The earliest known mention of bagels dates back to 1610 in Jewish community ordinances in Kraków, Poland.',
      'The hole in the middle was traditionally thought to help with transportation (strung on dowels) and to allow for more even cooking.',
      'Bagels were brought to the United States by immigrant Polish Jews and became strongly associated with New York City.',
      'Boiling the bagel before baking gelatinizes the starch on the surface, resulting in the chewy texture.',
      'Montreal-style bagels are a distinct variation that are boiled in honey-sweetened water and baked in wood-fired ovens.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Malt or sweetener (optional)',
    ],
  ),
  Bread(
    name: 'English Muffin',
    imagePath: 'assets/images/english_muffin.jpg',
    origin:
        'England/Wales, potentially 10th century (modern form 19th century)',
    description:
        'An English muffin is a small, round, and flat yeast-leavened bread, typically cooked on a griddle. They are known for their porous interior ("nooks and crannies") and are often split horizontally, toasted, and served with butter or other toppings.',
    facts: [
      'While their roots may be older, the English muffin as commonly known today was popularized by Samuel Bath Thomas in New York City in the late 19th century.',
      'They are cooked on a griddle rather than baked in an oven, contributing to their unique texture.',
      'The "nooks and crannies" are created by the relatively wet dough and the cooking process.',
      'In the UK, they are often simply called "muffins" or "breakfast muffins" to distinguish them from American-style cupcakes.',
      'English muffins are a key component of Eggs Benedict.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Water',
      'Yeast',
      'Salt',
      'Sugar (optional)',
      'Butter (optional)',
    ],
  ),
  Bread(
    name: 'Lavash',
    imagePath: 'assets/images/lavash.jpg',
    origin: 'Armenia / Iran / West Asia, ancient times',
    description:
        'Lavash is a thin flatbread, usually leavened, traditionally baked in a tandoor (tonir) or on a sajj. It is common in the cuisines of South Caucasus, West Asia, and areas around the Caspian Sea, particularly Armenia, Azerbaijan, Iran, and Turkey.',
    facts: [
      'Lavash was inscribed on the UNESCO Representative List of the Intangible Cultural Heritage of Humanity as "an expression of Armenian culture" in 2014, though its origin is debated and claimed by several regional cultures.',
      'Traditional lavash is made by stretching the dough very thin and slapping it onto the hot walls of a clay oven (tonir).',
      'It can be soft and pliable when fresh, or dried and stored for a long time, becoming cracker-like.',
      'Dried lavash can be rehydrated by sprinkling with water.',
      'In Armenia, it is traditional for the mother of the groom to feed the newlywed couple lavash and honey.',
    ],
    ingredients: [
      'Flour',
      'Water',
      'Yeast (sometimes unleavened)',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Arepa',
    imagePath: 'assets/images/arepa.jpg',
    origin: 'Colombia or Venezuela (Mesoamerica), pre-Columbian times',
    description:
        'An arepa is a flat, round, unleavened patty made of ground maize dough. It is a staple in Colombian and Venezuelan cuisine, commonly grilled, baked, fried, or boiled, and often split and filled with various ingredients like cheese, meats, or avocado.',
    facts: [
      'Arepas originated from indigenous peoples in the region now covering Colombia and Venezuela before Spanish colonization.',
      'The word "arepa" is believed to come from the indigenous Cumanagoto word "erepa" meaning "corn cake".',
      'Modern arepas are often made with pre-cooked corn flour (masarepa or masa al instante) which simplifies preparation.',
      'There is a friendly debate between Colombia and Venezuela about the exact origin of the arepa.',
      'Arepas vary widely in size, thickness, and filling depending on the region.',
    ],
    ingredients: [
      'Pre-cooked corn flour (Masarepa)',
      'Water',
      'Salt',
      'Oil or butter (optional)',
    ],
  ),
  Bread(
    name: 'Damper',
    imagePath: 'assets/images/damper.jpg',
    origin: 'Australia, early European settlers',
    description:
        'Damper is a traditional thick soda bread made from wheat flour, salt, and water, historically baked by early European settlers in Australia over the coals of a campfire. It is often served with butter, jam, or golden syrup.',
    facts: [
      'Damper was a staple for stockmen and travelers in remote areas due to its simple ingredients and campfire cooking method.',
      'The name "damper" might relate to "damping down" a fire or "damping" the appetite.',
      'While traditionally unleavened, some historical accounts suggest natural leavening if the dough was left overnight.',
      'It is considered an iconic symbol of Australian bush life.',
      'Similar hearth breads exist in other cultures, but damper is uniquely Australian.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Salt',
      'Butter (optional)',
    ],
  ),
  Bread(
    name: 'Anadama Bread',
    imagePath: 'assets/images/anadama_bread.jpg',
    origin: 'United States (New England), before 1850',
    description:
        'Anadama bread is a traditional yeast bread from New England, USA, made with wheat flour, cornmeal, and molasses. It has a slightly sweet flavor and a dense, tender crumb with a distinctive dark color from the molasses.',
    facts: [
      'Folklore attributes the name "Anadama" to a fisherman cursing his wife, Anna, while making the bread ("Anna, damn her!").',
      'It is believed to have originated in the coastal fishing communities of Maine and Massachusetts.',
      'The combination of cornmeal and molasses gives it its unique texture and flavor.',
      'Anadama bread was commercially produced and widely available in the Cape Ann area of Massachusetts in the 20th century.',
      'It is a variation of early American brown bread recipes.',
    ],
    ingredients: [
      'Wheat flour',
      'Cornmeal',
      'Molasses',
      'Water',
      'Yeast',
      'Salt',
      'Butter or shortening',
    ],
  ),
  Bread(
    name: 'Pan de Sal',
    imagePath: 'assets/images/pan_de_sal.jpg',
    origin: 'Philippines, 16th century (Spanish colonial era)',
    description:
        'Pandesal (or pan de sal) is a staple bread roll in the Philippines, commonly eaten for breakfast. Despite its name meaning "salt bread" in Spanish, it is typically slightly sweet and has a soft, pillowy texture, often coated in fine breadcrumbs.',
    facts: [
      'Its name comes from the Spanish "pan de sal", but it evolved from a local adaptation of the French baguette brought by the Spanish.',
      'It is traditionally rolled into logs, portioned, and then rolled in breadcrumbs before baking.',
      'Pandesal is most commonly served warm and is often dipped in coffee or hot chocolate.',
      'Its texture and taste are similar to Puerto Rican pan de agua or Mexican bolillos.',
      'Modern variations include fillings like ube and cheese, or mixing in ingredients like malunggay (moringa) leaves.',
    ],
    ingredients: [
      'Wheat flour',
      'Yeast',
      'Sugar',
      'Salt',
      'Oil',
      'Water',
      'Breadcrumbs (for coating)',
    ],
  ),
  Bread(
    name: 'Bolo do Caco',
    imagePath: 'assets/images/bolo_do_caco.jpg',
    origin: 'Madeira, Portugal',
    description:
        'Bolo do Caco is a circular Madeiran flatbread traditionally cooked on a hot basalt stone slab called a "caco". It is made with wheat flour and sweet potato, giving it a slightly sweet flavor and soft interior.',
    facts: [
      'The name translates to "cake of the caco", referring to its shape and cooking surface.',
      'The addition of sweet potato contributes to its unique texture and moisture.',
      'Traditionally cooked on a hot stone, it can also be made on a griddle or heavy pan.',
      'It is typically served warm, often slathered with garlic butter, and is also used for sandwiches.',
      'Its origins may have Arabic influences.',
    ],
    ingredients: [
      'Wheat flour',
      'Sweet potato',
      'Yeast',
      'Water',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Mantou',
    imagePath: 'assets/images/mantou.jpg',
    origin: 'China, potentially Qin Dynasty (3rd century BCE)',
    description:
        'Mantou are plain, steamed buns made from wheat flour, water, and a leavening agent. They are a staple carbohydrate in Northern China, typically eaten as a side with meals, contrasting with rice which is more common in the south.',
    facts: [
      'Mantou predates baozi (filled steamed buns), with the term "mantou" originally referring to both filled and unfilled buns.',
      'The history is often linked to military strategist Zhu Geliang in the Three Kingdoms period, though evidence of steamed breads is older.',
      'Northern Chinese mantou are generally denser and chewier, while Southern variations can be softer and slightly sweeter.',
      'Steaming results in a soft, smooth, and white exterior without a crust.',
      'Unlike many Western breads, mantou often use alkali (like baking soda) in addition to or instead of yeast, especially with traditional sourdough starters, to neutralize sourness.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast or Sourdough starter',
      'Baking soda (optional)',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Tiger Bread',
    imagePath: 'assets/images/tiger_bread.jpg',
    origin: 'Netherlands, at least since the 1930s',
    description:
        'Tiger bread, also known as Dutch Crunch, is a bread characterized by its unique mottled crust. This crust is created by painting a rice paste onto the surface of the loaf before baking, which cracks during cooking to resemble tiger stripes.',
    facts: [
      'The distinctive pattern is made from a paste of rice flour, sesame oil, and sometimes other ingredients, painted onto the dough.',
      'As the bread bakes and expands, the rice paste dries and cracks, creating the "tiger" or "giraffe" pattern.',
      'The interior of the bread is typically soft, providing a contrast to the crispy crust.',
      'In the UK, the supermarket Sainsbury\'s famously renamed it "giraffe bread" after a child suggested it looked more like a giraffe pattern.',
      'The technique can be applied to various shapes of bread, though it is commonly seen on loaves or rolls.',
    ],
    ingredients: [
      'Wheat flour (for the bread)',
      'Water (for the bread)',
      'Yeast (for the bread)',
      'Salt (for the bread)',
      'Rice flour (for the topping)',
      'Sesame oil (for the topping)',
      'Yeast (for the topping)',
      'Sugar (for the topping)',
    ],
  ),
  Bread(
    name: 'Fougasse',
    imagePath: 'assets/images/fougasse.jpg',
    origin: 'France (Provence), Ancient Rome',
    description:
        'Fougasse is a type of flatbread typically associated with Provence, France, but found in various forms across the Mediterranean. It is often slashed before baking to resemble an ear of wheat or a tree and can be flavored with ingredients like olives, herbs, or cheese.',
    facts: [
      'Fougasse is a variation of the Roman panis focacius, the same origin as focaccia.',
      'The shape with cuts isn\'t just decorative; it increases the crust-to-crumb ratio and helps the bread bake quickly.',
      'In some regions, the readiness of the fougasse was used to test the temperature of the wood-fired oven before baking larger loaves.',
      'It can be sweet or savory and is often served with soups or stews.',
      'The name comes from the Latin word "focus" meaning "hearth", indicating it was traditionally cooked on the hearth.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Olive oil',
      'Herbs (optional)',
      'Olives (optional)',
    ],
  ),
  Bread(
    name: 'Parker House Roll',
    imagePath: 'assets/images/parker_house_roll.jpg',
    origin: 'United States (Massachusetts), 1870s',
    description:
        'A Parker House roll is a bread roll made by flattening a circle of dough, brushing it with butter, and folding it in half. They are known for their soft, buttery texture and slight sweetness.',
    facts: [
      'They were created at the Omni Parker House Hotel in Boston, Massachusetts.',
      'A popular, though likely apocryphal, story suggests a baker threw unfinished rolls into the oven in anger, resulting in their distinctive shape.',
      'The key to their tenderness is a high ratio of butter and sometimes milk or cream.',
      'They are a classic American dinner roll.',
      'The folding method creates a layered, soft interior.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Yeast',
      'Sugar',
      'Salt',
      'Eggs (optional)',
    ],
  ),
  Bread(
    name: 'Bannock',
    imagePath: 'assets/images/bannock.jpg',
    origin: 'Scotland, ancient times (modern form variations globally)',
    description:
        'Bannock is a varied range of flat quick breads or yeast-leavened breads native to Scotland and also adopted and adapted by Indigenous peoples in North America. Traditional bannocks were made from barley, oats, or peasemeal and cooked on a griddle.',
    facts: [
      'The word "bannock" comes from the Scottish Gaelic "bannach," possibly from the Latin "panis" meaning bread.',
      'Historically, bannocks were cooked on a hot stone or griddle (a "bakestone").',
      'Scottish bannocks can be sweet or savory and are often associated with holidays like Hogmanay.',
      'In North America, Indigenous communities developed their own versions of bannock, often made with wheat flour and fried, baked, or cooked over an open fire.',
      'Different regions and families have their own traditional bannock recipes and cooking methods.',
    ],
    ingredients: [
      'Wheat flour or other grain flours (barley, oat, cornmeal)',
      'Water or milk',
      'Fat (butter, lard, or oil)',
      'Baking powder or soda (for quick bread)',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Crumpet',
    imagePath: 'assets/images/crumpet.jpg',
    origin: 'United Kingdom, potentially Anglo-Saxon period',
    description:
        'A crumpet is a small, round griddle cake made from an unsweetened batter of water or milk, flour, and yeast. They are characterized by their porous, flat top and are typically toasted and served with butter or other toppings.',
    facts: [
      'Early crumpets were likely hard cakes cooked on a griddle, becoming softer with the introduction of yeast.',
      'Their distinctive holes are formed by the rising action of the yeast and trapped air bubbles during cooking.',
      'They are traditionally cooked in a metal ring on a griddle to maintain their shape.',
      'Crumpets are a popular breakfast or tea-time food in the UK and Commonwealth countries.',
      'The name "crumpet" may be related to the Welsh word "crempog" or the Old English "crompeht" meaning "crumpled cake".',
    ],
    ingredients: [
      'Wheat flour',
      'Water or milk',
      'Yeast',
      'Salt',
      'Baking soda (optional)',
    ],
  ),
  Bread(
    name: 'Matzo',
    imagePath: 'assets/images/matzo.jpg',
    origin: 'Ancient Middle East (Jewish tradition), thousands of years ago',
    description:
        'Matzo is an unleavened flatbread traditionally eaten by Jews during the Passover holiday. It is made solely from flour and water and baked very quickly to prevent fermentation.',
    facts: [
      'Eating matzo during Passover commemorates the hurried departure of the Israelites from Egypt, where they did not have time for their bread dough to rise.',
      'According to Jewish law, the process from the moment water is mixed with flour until the matzo is baked cannot exceed 18 minutes to prevent leavening.',
      'It is also known as the "bread of affliction".',
      'Matzo is a key component in dishes like matzo ball soup and matzo brei.',
      'There are different varieties, including egg matzo and whole wheat matzo, though traditional matzo is just flour and water.',
    ],
    ingredients: [
      'Wheat flour (or other permitted grains)',
      'Water',
    ],
  ),
  Bread(
    name: 'Roti Canai',
    imagePath: 'assets/images/roti_canai.jpg',
    origin: 'Malaysia / India, 20th century',
    description:
        'Roti Canai is a flatbread dish popular in Malaysia, Brunei, Indonesia, Singapore, and Thailand. It is an Indian-influenced flatbread made from flour, water, eggs, and fat, and is traditionally pan-fried.',
    facts: [
      'The dough is repeatedly folded and flattened, often by tossing and stretching, to create thin layers.',
      'The name "roti" means bread in Hindi, Urdu, Malay, and Indonesian, and "canai" may refer to the city of Chennai (formerly Madras) or the word for rolling the dough.',
      'It is typically served with dal (lentil curry) or other curries.',
      'Variations include Roti Telur (with egg), Roti Pisang (with banana), and Murtabak (stuffed variety).',
      'A skilled Roti Canai maker can stretch and flip the dough into a very thin sheet before folding.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Egg',
      'Ghee or oil',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Scone',
    imagePath: 'assets/images/scone.jpg',
    origin: 'Scotland, 16th century',
    description:
        'A scone is a single-serving baked good, usually made of wheat or oatmeal with baking powder as a leavening agent, and baked on sheet pans. They are often lightly sweetened and can contain dried fruit.',
    facts: [
      'Early scones were round and flat, cooked on a griddle, and cut into triangles (called "पीठ" or "scones").',
      'The modern baked scone made with baking powder became popular after this leavening agent became widely available.',
      'Scones are a foundational element of a traditional cream tea or afternoon tea.',
      'There is a long-standing debate about how to pronounce "scone" (rhyming with "gone" or "cone").',
      'They are typically served with clotted cream and jam (often strawberry).',
    ],
    ingredients: [
      'Wheat flour',
      'Butter',
      'Milk or buttermilk',
      'Baking powder',
      'Sugar',
      'Salt',
      'Dried fruit (optional)',
    ],
  ),
  Bread(
    name: 'Cornbread',
    imagePath: 'assets/images/cornbread.jpg',
    origin: 'Southern United States, indigenous origins',
    description:
        'Cornbread is a quick bread made from cornmeal. It is a staple in Southern U.S. cuisine, known for its crumbly texture and distinct corn flavor. It can be baked in a pan, skillet, or as muffins.',
    facts: [
      'Cornbread originated from Native American cooking, who used ground maize long before European settlers arrived.',
      'Early American colonists adopted and adapted cornbread recipes.',
      'Southern-style cornbread is traditionally made without sugar and cooked in a cast-iron skillet, resulting in a crispy crust.',
      'Northern-style cornbread often includes sugar and is more cake-like.',
      'It is commonly served with chili, stews, or fried chicken.',
    ],
    ingredients: [
      'Cornmeal',
      'Wheat flour (optional)',
      'Milk or buttermilk',
      'Eggs',
      'Fat (butter, oil, or bacon grease)',
      'Baking powder or soda',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Paneer Naan',
    imagePath: 'assets/images/paneer_naan.jpg',
    origin: 'India',
    description:
        'Paneer Naan is a variation of traditional Indian naan bread, stuffed with spiced crumbled paneer (Indian cottage cheese) before being baked in a tandoor or on a griddle.',
    facts: [
      'It is a popular and richer version of naan, often served with rich gravies and curries.',
      'The paneer filling can be spiced with ingredients like cumin, coriander, green chilies, and cilantro.',
      'The bread is often brushed with butter or ghee after baking.',
      'It is a common item on menus in Indian restaurants worldwide.',
      'Making Paneer Naan involves carefully stuffing the dough without the filling leaking out during cooking.',
    ],
    ingredients: [
      'Wheat flour',
      'Yogurt',
      'Butter or Ghee',
      'Yeast',
      'Water',
      'Salt',
      'Paneer (Indian cottage cheese)',
      'Spices (cumin, coriander, chili, etc.)',
      'Cilantro (optional)',
    ],
  ),
  Bread(
    name: 'King Cake',
    imagePath: 'assets/images/king_cake.jpg',
    origin: 'France/Spain (tradition), New Orleans (modern form)',
    description:
        'King Cake is a ring-shaped cake-like bread associated with Epiphany (King\'s Day) and Mardi Gras celebrations, particularly in the Southern United States, especially New Orleans. It is typically decorated with colored icing and sugars in purple, green, and gold.',
    facts: [
      'The tradition originated from the celebration of Epiphany, honoring the Three Kings visiting Baby Jesus.',
      'A small plastic baby (or sometimes a bean or coin) is hidden inside the cake, and the person who finds it is said to have good luck and is often responsible for providing the next King Cake or hosting the next party.',
      'The colors represent justice (purple), faith (green), and power (gold).',
      'While called a "cake", it often has a texture closer to a sweet, enriched bread.',
      'The Mardi Gras season in New Orleans begins on Epiphany (January 6th) and ends on Fat Tuesday, with King Cake being a central part of celebrations during this time.',
    ],
    ingredients: [
      'Wheat flour',
      'Yeast',
      'Milk',
      'Butter',
      'Eggs',
      'Sugar',
      'Salt',
      'Cinnamon',
      'Icing',
      'Colored sugars (purple, green, gold)',
      'Plastic baby',
    ],
  ),
  Bread(
    name: 'Quesadilla (as a bread base)',
    imagePath: 'assets/images/quesadilla_base.jpg',
    origin: 'Mexico',
    description:
        'While often thought of as a dish, the base of a traditional quesadilla is a tortilla (usually corn or wheat) that is heated and filled, primarily with cheese. The tortilla itself is a fundamental bread in Mexican cuisine.',
    facts: [
      'The name "quesadilla" comes from "queso" (cheese) and "tortilla".',
      'In some regions of Mexico, quesadillas are made with masa dough patties that are filled and then cooked, similar to a thick, filled tortilla.',
      'The melting cheese acts as a binder, holding the folded tortilla together.',
      'Quesadillas can be cooked on a comal (a flat griddle) or in a pan.',
      'While cheese is the primary filling, other ingredients like meats, vegetables, and beans are often added.',
    ],
    ingredients: [
      'Corn flour (Masa Harina) or Wheat flour',
      'Water',
      'Salt',
      'Cheese',
      'Various fillings (optional)',
    ],
  ),
  Bread(
    name: 'Laobing',
    imagePath: 'assets/images/laobing.jpg',
    origin: 'China (Northern)',
    description:
        'Laobing is a large, round, unleavened flatbread popular in Northern China. It is made from wheat flour, hot water, and sometimes oil, resulting in a chewy interior and a slightly crisp exterior.',
    facts: [
      'The name "laobing" translates to "old cake" or "old bread".',
      'Hot water dough is used, which inhibits gluten development and results in a softer, less elastic dough compared to cold water dough.',
      'It is often cooked in a large, flat pan or griddle.',
      'Laobing can be eaten on its own, used to wrap fillings, or cut into pieces and added to stir-fries.',
      'Variations can include scallions or other flavorings mixed into the dough or layered within it.',
    ],
    ingredients: [
      'Wheat flour',
      'Hot water',
      'Oil (optional)',
      'Salt',
      'Scallions (optional)',
    ],
  ),
  Bread(
    name: 'Parenyica',
    imagePath: 'assets/images/parenyica.jpg',
    origin: 'Slovakia',
    description:
        'Parenyica is a traditional Slovak steamed cheese that is often braided and shaped. While primarily a cheese, it is prepared in a way that gives it a bread-like texture and is often served similarly to bread.',
    facts: [
      'The name "parenyica" comes from the Slovak word "pariť" meaning "to steam".',
      'It is made from sheep\'s milk cheese (sometimes mixed with cow\'s milk).',
      'The cheese curds are heated and stretched, then formed into shape and often braided before being steamed.',
      'It has a mild, slightly salty flavor and a rubbery, stringy texture.',
      'Parenyica is a protected geographical indication (PGI) in the European Union.',
    ],
    ingredients: [
      'Sheep\'s milk cheese',
      'Salt',
      'Rennet',
    ],
  ),
  Bread(
    name: 'Vetkoek',
    imagePath: 'assets/images/vetkoek.jpg',
    origin: 'South Africa',
    description:
        'Vetkoek (Afrikaans for "fat cake") is a traditional South African fried dough bread. It is similar to a doughnut but is typically unsweetened and often filled with savory mince or served with butter and jam.',
    facts: [
      'It is a popular and affordable street food in South Africa.',
      'The dough is leavened with yeast and deep-fried until golden brown.',
      'The exterior is crispy, while the interior is soft and fluffy.',
      'Besides savory mince, common fillings include syrup, honey, or political debate (informally referred to as "political vetkoek").',
      'Vetkoek is a staple in many South African households and is often prepared for informal gatherings.',
    ],
    ingredients: [
      'Wheat flour',
      'Yeast',
      'Water',
      'Salt',
      'Sugar (optional)',
      'Oil (for frying)',
    ],
  ),
  Bread(
    name: 'Kanelbullar',
    imagePath: 'assets/images/kanelbullar.jpg',
    origin: 'Sweden, 20th century',
    description:
        'Kanelbullar are Swedish cinnamon buns, a type of sweet roll flavored with cinnamon and sugar, often with cardamom. They are a staple of Swedish fika (coffee break).',
    facts: [
      'October 4th is Kanelbullens Dag (Cinnamon Bun Day) in Sweden, established in 1999.',
      'The dough is typically enriched with butter, milk, and sugar.',
      'The filling is a mixture of butter, cinnamon, and sugar, often spread on the dough before rolling and slicing.',
      'They are often topped with pearl sugar or a simple glaze.',
      'While similar to cinnamon rolls in other countries, Swedish Kanelbullar often have a distinct cardamom flavor and a slightly less sweet profile.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Yeast',
      'Sugar',
      'Salt',
      'Cardamom',
      'Cinnamon',
      'Pearl sugar or glaze',
    ],
  ),
  Bread(
    name: 'Lefse',
    imagePath: 'assets/images/lefse.jpg',
    origin: 'Norway',
    description:
        'Lefse is a traditional Norwegian flatbread made from potatoes, flour, butter, and milk or cream. It is cooked on a large, flat griddle.',
    facts: [
      'Lefse is a staple during the Christmas season in Norway and in Norwegian-American communities.',
      'The dough is rolled very thin using a special grooved rolling pin and a long turning stick.',
      'It is cooked quickly on a hot, dry griddle until lightly browned spots appear.',
      'Lefse can be served warm with butter and sugar, or with savory fillings like lutefisk or gravlax.',
      'There are regional variations in Norway, including different textures and ingredients.',
    ],
    ingredients: [
      'Cooked potatoes',
      'Wheat flour',
      'Butter',
      'Milk or cream',
      'Salt',
      'Sugar (optional)',
    ],
  ),
  Bread(
    name: 'Bazlama',
    imagePath: 'assets/images/bazlama.jpg',
    origin: 'Turkey',
    description:
        'Bazlama is a single-layer, flat, circular Turkish bread made from wheat flour, water, yeast, and salt. It is typically cooked on a griddle or in a clay oven.',
    facts: [
      'It is a popular everyday bread in Turkey, often served at breakfast or with kebabs and other dishes.',
      'The dough is soft and slightly elastic, resulting in a light and airy bread.',
      'Bazlama often puffs up during cooking, creating a pocket that can be filled.',
      'It is best served fresh and warm.',
      'Regional variations may include adding yogurt or milk to the dough.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Yogurt or milk (optional)',
    ],
  ),
  Bread(
    name: 'Khachapuri',
    imagePath: 'assets/images/khachapuri.jpg',
    origin: 'Georgia',
    description:
        'Khachapuri is a traditional Georgian dish of cheese-filled bread. There are several varieties, with the most famous being Imeruli (round) and Adjaruli (boat-shaped with an egg and butter in the center).',
    facts: [
      'The name comes from the Georgian words "khacha" (cheese curd) and "puri" (bread).',
      'It is a national dish of Georgia.',
      'Adjaruli Khachapuri is often served with a raw egg and a pat of butter placed in the center after baking, which are then mixed into the hot cheese by the diner.',
      'Different regions of Georgia have their own distinct types of Khachapuri with varying shapes and fillings.',
      'Khachapuri is recognized by UNESCO as part of the Intangible Cultural Heritage of Georgia.',
    ],
    ingredients: [
      'Wheat flour',
      'Yeast',
      'Water',
      'Salt',
      'Cheese (various types, often a mix of sulguni and imeruli)',
      'Egg (for Adjaruli)',
      'Butter (for Adjaruli)',
    ],
  ),
  Bread(
    name: 'Bolani',
    imagePath: 'assets/images/bolani.jpg',
    origin: 'Afghanistan',
    description:
        'Bolani is a thin, unleavened Afghan flatbread typically filled with ingredients like potatoes, lentils, pumpkin, or leeks, and then fried or baked.',
    facts: [
      'It is a popular street food and appetizer in Afghanistan.',
      'The dough is made from simple ingredients: flour, water, and salt.',
      'The filling is spread over half of the dough circle, and the other half is folded over to create a半月形 (half-moon) shape.',
      'Bolani is often served with yogurt or a mint-yogurt sauce.',
      'It is commonly prepared for special occasions and gatherings.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Salt',
      'Oil (for frying or baking)',
      'Various fillings (potatoes, lentils, pumpkin, leeks, etc.)',
    ],
  ),
  Bread(
    name: 'Piadina',
    imagePath: 'assets/images/piadina.jpg',
    origin: 'Italy (Romagna)',
    description:
        'Piadina Romagnola is a thin Italian flatbread traditionally made with wheat flour, lard or olive oil, water, and salt. It is cooked on a terracotta griddle or a flat pan and typically folded and filled with various ingredients.',
    facts: [
      'It is a staple street food from the Romagna region of Italy.',
      'Historically, lard was a common ingredient, but olive oil is often used now.',
      'It is cooked quickly until spotted with brown marks.',
      'Common fillings include squacquerone cheese, prosciutto, and arugula.',
      'Piadina has Protected Geographical Indication (PGI) status in Europe.',
    ],
    ingredients: [
      'Wheat flour',
      'Lard or olive oil',
      'Water',
      'Salt',
      'Baking soda (sometimes)',
    ],
  ),
  Bread(
    name: 'Ketupat',
    imagePath: 'assets/images/ketupat.jpg',
    origin:
        'Southeast Asia (Indonesia, Malaysia, Brunei, Singapore, Philippines)',
    description:
        'Ketupat is a rice cake wrapped in a woven palm leaf pouch, then boiled. As the rice cooks, it expands to fill the pouch, creating a dense, firm rice dumpling. While not a bread made from flour, it serves a similar carbohydrate role and has a unique preparation method.',
    facts: [
      'It is traditionally served during festive occasions, particularly Eid al-Fitr (after Ramadan).',
      'The weaving of the palm leaves is an intricate process, often done by hand.',
      'The leaf pouch gives the rice a distinct aroma and shape.',
      'Ketupat is often served with rendang, satay, or gado-gado.',
      'Different regions may use different types of palm leaves or weaving patterns.',
    ],
    ingredients: [
      'Rice',
      'Young palm leaves (for weaving)',
      'Water',
    ],
  ),
  Bread(
    name: 'Slider Bun',
    imagePath: 'assets/images/slider_bun.jpg',
    origin: 'United States, 20th century',
    description:
        'A slider bun is a small bread roll, typically soft and slightly sweet, designed specifically for making sliders (small hamburgers or sandwiches). They are often sold connected in a tray.',
    facts: [
      'The term "slider" for a small hamburger is believed to have originated with White Castle restaurants in the 1940s.',
      'Slider buns are often steamed before serving to make them even softer.',
      'Their small size makes them ideal for serving as appetizers or in larger quantities.',
      'Many recipes for slider buns are based on enriched doughs, similar to brioche or challah but less rich.',
      'The connected nature of some slider buns allows for easy assembly of multiple sliders at once.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Eggs',
      'Sugar',
      'Yeast',
      'Salt',
    ],
  ),
  Bread(
    name: 'Frybread',
    imagePath: 'assets/images/frybread.jpg',
    origin: 'Native American (United States)',
    description:
        'Frybread is a flat dough, either leavened or unleavened, that is deep-fried. It is a significant food in Native American communities in the United States, often served plain, with savory toppings like ground meat and beans (creating an "Indian Taco"), or with sweet toppings like honey or jam.',
    facts: [
      'Frybread\'s origins are linked to the forced displacement of Native Americans and the government rations provided, which included flour, sugar, and lard.',
      'It is considered a symbol of Native American resilience and cultural identity, though its origins are tied to hardship.',
      'Different tribes and families have their own variations and recipes for frybread.',
      'It is commonly served at powwows and cultural gatherings.',
      'The texture can range from crispy and thin to soft and fluffy depending on the recipe and cooking method.',
    ],
    ingredients: [
      'Wheat flour',
      'Water or milk',
      'Baking powder (optional)',
      'Salt',
      'Lard or oil (for frying)',
    ],
  ),
  Bread(
    name: 'Shokupan',
    imagePath: 'assets/images/shokupan.jpg',
    origin: 'Japan',
    description:
        'Shokupan, also known as Japanese Milk Bread, is a soft, fluffy, and slightly sweet white bread. Its characteristic texture is often achieved using the Tangzhong method, a cooked milk and flour paste added to the dough.',
    facts: [
      'The name "Shokupan" translates simply to "eating bread".',
      'The Tangzhong method helps the bread retain moisture, resulting in its incredibly soft and tender crumb that stays fresh longer.',
      'It is a staple bread in Japanese households, commonly used for sandwiches and toast.',
      'Shokupan loaves are typically baked in a lidded Pullman pan to create a perfectly square shape.',
      'It has gained international popularity for its superior softness compared to many Western white breads.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Sugar',
      'Butter',
      'Yeast',
      'Salt',
      'Tangzhong (flour and milk/water paste)',
    ],
  ),
  Bread(
    name: 'Bara Brith',
    imagePath: 'assets/images/bara_brith.jpg',
    origin: 'Wales',
    description:
        'Bara Brith is a traditional Welsh fruit loaf or cake, often referred to as "speckled bread" due to the dried fruit it contains. It is typically made with dried fruits like raisins, currants, and candied peel, and flavored with tea.',
    facts: [
      'The name "Bara Brith" means "speckled bread" in Welsh.',
      'Traditionally, the dried fruit is soaked in hot tea overnight before being added to the dough.',
      'It is often served sliced and buttered with a cup of tea.',
      'While it contains fruit and can be sweet, its texture is generally bread-like rather than cake-like.',
      'Bara Brith recipes vary, with some using yeast and others using baking powder.',
    ],
    ingredients: [
      'Wheat flour',
      'Dried fruit (raisins, currants, candied peel)',
      'Tea',
      'Sugar',
      'Butter',
      'Egg (optional)',
      'Yeast or Baking powder',
      'Mixed spice',
    ],
  ),
  Bread(
    name: 'Melonpan',
    imagePath: 'assets/images/melonpan.jpg',
    origin: 'Japan',
    description:
        'Melonpan is a sweet Japanese bread roll covered in a thin layer of crisp cookie dough. It is characterized by a criss-cross pattern scored into the cookie layer before baking, often resembling the rind of a melon (though it does not typically taste like melon).',
    facts: [
      'The name comes from its appearance, which is thought to resemble a rock melon or cantaloupe.',
      'The interior is a soft, fluffy bread dough, while the exterior is a sugary, crispy cookie crust.',
      'It is a popular pastry found in bakeries and convenience stores across Japan.',
      'Some variations include a filling, such as chocolate or flavored cream.',
      'The cookie layer is typically made with flour, sugar, butter, and eggs.',
    ],
    ingredients: [
      'Wheat flour (for bread and cookie)',
      'Milk',
      'Butter',
      'Eggs',
      'Sugar',
      'Yeast (for bread)',
      'Salt',
      'Baking powder (for cookie)',
      'Vanilla extract (optional)',
    ],
  ),
  Bread(
    name: 'Pan de Muerto',
    imagePath: 'assets/images/pan_de_muerto.jpg',
    origin: 'Mexico',
    description:
        'Pan de Muerto ("Bread of the Dead") is a traditional Mexican sweet bread baked for the Day of the Dead (Día de Muertos) celebration. It is typically a soft, often orange-flavored sweet roll decorated with bone-shaped pieces of dough.',
    facts: [
      'It is placed on ofrendas (altars) to honor deceased loved ones.',
      'The bone shapes are said to represent the bones of the departed.',
      'A small ball of dough on top often symbolizes a skull or the tears of the living.',
      'The orange blossom water or anise seeds used in the dough give it a distinctive aroma and flavor.',
      'Different regions in Mexico have variations in the recipe and decoration of Pan de Muerto.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Eggs',
      'Sugar',
      'Yeast',
      'Salt',
      'Orange blossom water or anise seeds',
      'Orange zest (optional)',
      'Sugar (for coating)',
    ],
  ),
  Bread(
    name: 'Babka',
    imagePath: 'assets/images/babka.jpg',
    origin: 'Eastern Europe (Jewish communities in Ukraine and Poland)',
    description:
        'Babka is a sweet, braided bread or cake, typically filled with chocolate, cinnamon, or fruit. It originated in the Jewish communities of Eastern Europe and is now popular in many parts of the world.',
    facts: [
      'The name "babka" comes from the Slavic word "babcia," meaning grandmother, possibly referring to its shape resembling a grandmother\'s skirt.',
      'It is made from an enriched dough, similar to brioche.',
      'The dough is rolled out, filled, rolled into a log, and then often braided before baking.',
      'Chocolate babka is one of the most popular varieties.',
      'Babka is known for its moist, swirled interior.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Eggs',
      'Sugar',
      'Yeast',
      'Salt',
      'Filling (chocolate, cinnamon, fruit, etc.)',
    ],
  ),
  Bread(
    name: 'Obi Non',
    imagePath: 'assets/images/obi_non.jpg',
    origin: 'Central Asia (Uzbekistan, Afghanistan)',
    description:
        'Obi Non is a traditional Central Asian flatbread, particularly popular in Uzbek and Afghan cuisine. It is a round, often thick, leavened bread typically baked in a tandoor oven and sometimes stamped with decorative patterns.',
    facts: [
      'It is a staple bread served with most meals in Uzbekistan and Afghanistan.',
      'The dough is relatively simple, made from flour, water, yeast, and salt.',
      'It has a slightly chewy interior and a firm crust from the tandoor baking.',
      'Decorative patterns are often pressed into the center of the loaf using a special tool (chekich).',
      'Freshly baked Obi Non has a wonderful aroma and is highly prized.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Milk (optional)',
      'Sesame or Nigella seeds (optional)',
    ],
  ),
  Bread(
    name: 'Pane Carasau',
    imagePath: 'assets/images/pane_carasau.jpg',
    origin: 'Sardinia, Italy, ancient times',
    description:
        'Pane Carasau is a traditional Sardinian flatbread that is very thin and crispy, often called "music paper bread" due to its texture. It is made from durum wheat flour, water, salt, and yeast, and baked twice.',
    facts: [
      'It was traditionally made by shepherds for its long shelf life, making it ideal for taking into the fields.',
      'The dough is rolled incredibly thin before the first baking.',
      'After the first bake, the inflated bread is split horizontally into two thin sheets, which are then baked again until crisp.',
      'It can be eaten dry or moistened slightly with water, wine, or broth before serving with food.',
      'Pane Carasau with tomato sauce and egg is known as Pane Frattau.',
    ],
    ingredients: [
      'Durum wheat flour',
      'Water',
      'Yeast',
      'Salt',
    ],
  ),
  Bread(
    name: 'Anpan',
    imagePath: 'assets/images/anpan.jpg',
    origin: 'Japan, 1875',
    description:
        'Anpan is a sweet Japanese bread roll typically filled with anko (red bean paste). It is one of the most popular and iconic pastries in Japan.',
    facts: [
      'Anpan was first made in 1875 during the Meiji period by a samurai, Yasubei Kimura, who wanted to create a bread that suited Japanese tastes.',
      'He used a sake yeast starter, which was more common in Japan at the time than Western bread yeasts.',
      'While red bean paste is the traditional filling, other fillings like white bean paste (shiroan), sesame paste (gomaan), chestnut paste (kurian), or flavored creams are also used.',
      'Anpan is often decorated with a garnish on top indicating the filling, such as a sesame seed for white bean paste or a poppy seed for red bean paste.',
      'It is a common snack or breakfast item in Japan.',
    ],
    ingredients: [
      'Wheat flour',
      'Milk',
      'Butter',
      'Eggs (optional)',
      'Sugar',
      'Yeast or Sake yeast starter',
      'Salt',
      'Anko (red bean paste)',
      'Sesame seeds or poppy seeds (for garnish)',
    ],
  ),
  Bread(
    name: 'Corn Tortilla',
    imagePath: 'assets/images/corn_tortilla.jpg',
    origin: 'Mesoamerica, potentially 3000 BCE',
    description:
        'A traditional tortilla made from masa harina (alkalized corn flour), water, and salt. It is a staple in Mexican cuisine, used for tacos, enchiladas, tostadas, and more. Corn tortillas are typically smaller and more pliable than wheat tortillas when fresh.',
    facts: [
      'Corn tortillas predate wheat tortillas in the Americas by thousands of years.',
      'The process of nixtamalization (treating corn with an alkaline solution) is crucial for making masa and improves the nutritional value and digestibility of the corn.',
      'They are naturally gluten-free.',
      'Freshly made corn tortillas have a distinct aroma and flavor.',
      'In Mexico, corn tortillas are often made fresh daily and are a fundamental part of the diet.',
    ],
    ingredients: [
      'Masa Harina (alkalized corn flour)',
      'Water',
      'Salt',
    ],
  ),
  Bread(
    name: 'Wheat Tortilla',
    imagePath: 'assets/images/wheat_tortilla.jpg',
    origin:
        'Northern Mexico / Southwestern United States, post-European contact',
    description:
        'A tortilla made from wheat flour, water, fat (like lard or vegetable shortening), and salt. Wheat tortillas are larger and more flexible than corn tortillas, making them ideal for burritos and wraps.',
    facts: [
      'Wheat tortillas became popular in areas where wheat was more readily available after European colonization.',
      'They are softer and more pliable than corn tortillas, especially when cold.',
      'The addition of fat contributes to their softness and flexibility.',
      'Wheat tortillas are widely used in Tex-Mex cuisine.',
      'They can be used for a variety of dishes beyond burritos, including quesadillas and chimichangas.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Shortening (lard or vegetable oil)',
      'Salt',
      'Baking powder (sometimes)',
    ],
  ),
  Bread(
    name: 'Bialy',
    imagePath: 'assets/images/bialy.jpg',
    origin: 'Poland (Białystok), 19th century',
    description:
        'A bialy is a small bread roll, similar to a bagel but without the hole. Instead, it has a depression in the center filled with cooked onions, sometimes with poppy seeds. Bialys are baked, not boiled and then baked like bagels.',
    facts: [
      'The name "bialy" is short for "bialostocki kuchen," meaning "Białystok cake" or "Białystok roll".',
      'They originated in Białystok, Poland, and were brought to the United States by Ashkenazi Jewish immigrants.',
      'Unlike bagels, bialys are baked directly without the boiling step, resulting in a softer texture.',
      'The onion filling is a key characteristic of a traditional bialy.',
      'Bialys are best eaten fresh, as they tend to become hard quickly.',
    ],
    ingredients: [
      'Wheat flour',
      'Water',
      'Yeast',
      'Salt',
      'Onions',
      'Poppy seeds (optional)',
    ],
  ),
  Bread(
    name: 'atanga',
    imagePath: 'assets/images/atanga.jpg',
    origin: 'East Africa (Kenya, Tanzania)',
    description:
        'Mandazi are a type of fried dough popular in East African cuisine. They are often flavored with coconut milk or cardamom and are typically triangular in shape.',
    facts: [
      'Mandazi are similar to doughnuts but are usually less sweet and are not typically glazed or filled.',
      'They are a common breakfast item or snack, often served with tea or coffee.',
      'The addition of coconut milk and cardamom gives them a distinctive East African flavor.',
      'The dough is usually rolled out and cut into triangles or squares before frying.',
      'Mandazi are a staple in many East African homes and are sold by street vendors.',
    ],
    ingredients: [
      'Wheat flour',
      'Sugar',
      'Yeast or Baking powder',
      'Coconut milk',
      'Cardamom',
      'Egg (optional)',
      'Oil (for frying)',
    ],
  ),
];
